// Справочные таблицы для модалки документации LOLZ API.
window.DOCS_REFERENCE = {
    apiBases: [
        { label: "Маркет API", url: "https://prod-api.lzt.market/", desc: "Поиск, покупка, баланс" },
        { label: "Форум API", url: "https://api.zelenka.guru/", desc: "Темы, посты, профиль" },
    ],
    steamGames: [
        { id: "730", name: "Counter-Strike 2 (CS2)" },
        { id: "570", name: "Dota 2" },
        { id: "440", name: "Team Fortress 2" },
        { id: "252490", name: "Rust" },
        { id: "578080", name: "PUBG: BATTLEGROUNDS" },
        { id: "304930", name: "Unturned" },
        { id: "232090", name: "Killing Floor 2" },
        { id: "322330", name: "Don't Starve Together" },
        { id: "753", name: "Steam (подарки / очки / картинки)" },
        { id: "107410", name: "Arma 3" },
        { id: "1174180", name: "Red Dead Redemption 2" },
        { id: "271590", name: "Grand Theft Auto V" },
        { id: "359550", name: "Rainbow Six Siege" },
        { id: "230410", name: "Warframe" },
        { id: "291550", name: "Brawlhalla" },
        { id: "381210", name: "Dead by Daylight" },
        { id: "252950", name: "Rocket League" },
        { id: "1599340", name: "Lost Ark" },
        { id: "1085660", name: "Destiny 2" },
        { id: "1245620", name: "Elden Ring" },
        { id: "1938090", name: "Call of Duty" },
        { id: "236390", name: "War Thunder" },
        { id: "1203220", name: "NBA 2K" },
        { id: "431960", name: "Wallpaper Engine" },
    ],
    marketPaths: [
        { path: "steam", name: "Steam / CS2 / Dota" },
        { path: "telegram", name: "Telegram" },
        { path: "discord", name: "Discord" },
        { path: "fortnite", name: "Fortnite" },
        { path: "riot", name: "Valorant / Riot" },
        { path: "mihoyo", name: "Genshin Impact / miHoYo" },
        { path: "roblox", name: "Roblox" },
        { path: "socialclub", name: "GTA V / Social Club" },
        { path: "mihoyo", name: "miHoYo (Genshin / Honkai / ZZZ)" },
        { path: "supercell", name: "Supercell" },
        { path: "epicgames", name: "Epic Games" },
        { path: "tiktok", name: "TikTok" },
        { path: "instagram", name: "Instagram" },
        { path: "minecraft", name: "Minecraft" },
        { path: "escape-from-tarkov", name: "Escape from Tarkov" },
        { path: "battlenet", name: "Battle.net" },
        { path: "vpn", name: "VPN" },
        { path: "gifts", name: "Подарки" },
    ],
    marketCategories: [
        { id: "1", name: "Steam" },
        { id: "3", name: "EA (Origin)" },
        { id: "4", name: "Warface" },
        { id: "5", name: "Uplay" },
        { id: "6", name: "LLM" },
        { id: "7", name: "Social Club" },
        { id: "8", name: "Hytale" },
        { id: "9", name: "Fortnite" },
        { id: "10", name: "Instagram" },
        { id: "11", name: "Battlenet" },
        { id: "12", name: "Epic Games" },
        { id: "13", name: "Riot / Valorant" },
        { id: "14", name: "World of Tanks" },
        { id: "15", name: "Supercell" },
        { id: "16", name: "WOT Blitz" },
        { id: "17", name: "miHoYo" },
        { id: "18", name: "Escape from Tarkov" },
        { id: "19", name: "VPN" },
        { id: "20", name: "TikTok" },
        { id: "22", name: "Discord" },
        { id: "24", name: "Telegram" },
        { id: "28", name: "Minecraft" },
        { id: "30", name: "Gifts" },
        { id: "31", name: "Roblox" },
    ],
    orderBy: [
        { value: "price_to_up", desc: "Сначала дешевле" },
        { value: "price_to_down", desc: "Сначала дороже" },
        { value: "pdate_to_down", desc: "Сначала новые лоты" },
        { value: "pdate_to_up", desc: "Сначала старые лоты" },
        { value: "pdate_to_down_upload", desc: "Недавно загруженные" },
        { value: "pdate_to_up_upload", desc: "Давно загруженные" },
        { value: "pdate_to_down_active", desc: "Недавно активные продавцы" },
        { value: "edate_to_up", desc: "Недавно отредактированные" },
        { value: "edate_to_down", desc: "Давно отредактированные" },
        { value: "title", desc: "По алфавиту названия" },
        { value: "auto_buy_diff_to_up", desc: "Разница автобая ↑" },
        { value: "auto_buy_diff_to_down", desc: "Разница автобая ↓" },
    ],
    currencies: [
        { code: "rub", name: "Рубль" },
        { code: "usd", name: "Доллар США" },
        { code: "eur", name: "Евро" },
        { code: "uah", name: "Гривна" },
        { code: "kzt", name: "Тенге" },
        { code: "byn", name: "Бел. рубль" },
        { code: "gbp", name: "Фунт" },
        { code: "cny", name: "Юань" },
        { code: "try", name: "Лира" },
        { code: "jpy", name: "Иена" },
        { code: "brl", name: "Реал" },
    ],
    emailTypes: [
        { value: "autoreg", desc: "Авторег почта" },
        { value: "native", desc: "Родная почта аккаунта" },
        { value: "no", desc: "Без почты" },
        { value: "no_market", desc: "Без почты маркета" },
    ],
    emailProviders: [
        { value: "mail_ru", desc: "Mail.ru" },
        { value: "rambler", desc: "Rambler" },
        { value: "outlook", desc: "Outlook / Hotmail" },
        { value: "firstmail", desc: "Firstmail" },
        { value: "notletters", desc: "Notletters" },
        { value: "other", desc: "Другой провайдер" },
    ],
    csgoRanks: [
        { value: "0", desc: "Без ранга / не калиброван" },
        { value: "1", desc: "Silver I" },
        { value: "2", desc: "Silver II" },
        { value: "3", desc: "Silver III" },
        { value: "4", desc: "Silver Elite" },
        { value: "5", desc: "Silver Elite Master" },
        { value: "7", desc: "Gold Nova I" },
        { value: "10", desc: "Master Guardian I" },
        { value: "13", desc: "DMG" },
        { value: "15", desc: "Legendary Eagle" },
        { value: "17", desc: "Supreme" },
        { value: "18", desc: "Global Elite" },
    ],
    valorantRanks: [
        { value: "3", desc: "Iron 1" },
        { value: "6", desc: "Bronze 1" },
        { value: "9", desc: "Silver 1" },
        { value: "12", desc: "Gold 1" },
        { value: "15", desc: "Platinum 1" },
        { value: "18", desc: "Diamond 1" },
        { value: "21", desc: "Ascendant 1" },
        { value: "24", desc: "Immortal 1" },
        { value: "27", desc: "Radiant" },
    ],
    telegramCountries: [
        { code: "RU", name: "Россия" },
        { code: "US", name: "США" },
        { code: "UA", name: "Украина" },
        { code: "KZ", name: "Казахстан" },
        { code: "BY", name: "Беларусь" },
        { code: "ID", name: "Индонезия" },
        { code: "TR", name: "Турция" },
        { code: "IN", name: "Индия" },
        { code: "DE", name: "Германия" },
        { code: "GB", name: "Великобритания" },
        { code: "CN", name: "Китай" },
        { code: "BR", name: "Бразилия" },
        { code: "PL", name: "Польша" },
        { code: "FR", name: "Франция" },
        { code: "VN", name: "Вьетнам" },
        { code: "PH", name: "Филиппины" },
        { code: "MY", name: "Малайзия" },
        { code: "UZ", name: "Узбекистан" },
        { code: "GE", name: "Грузия" },
        { code: "AM", name: "Армения" },
    ],
    valorantRegions: [
        { code: "EU", name: "Европа" },
        { code: "NA", name: "Северная Америка" },
        { code: "AP", name: "Азия / Тихий океан" },
        { code: "KR", name: "Корея" },
        { code: "BR", name: "Бразилия" },
        { code: "LATAM", name: "Латинская Америка" },
    ],
    forumSections: [
        { id: "84", name: "Тестовый раздел (разработка)" },
        { id: "8", name: "Оффтопик" },
        { id: "83", name: "Python / скрипты" },
        { id: "801", name: "Маркет — обсуждения" },
        { id: "9", name: "Продажа аккаунтов" },
        { id: "775", name: "Конкурсы и розыгрыши" },
        { id: "20", name: "Программирование" },
        { id: "766", name: "Софт и утилиты" },
    ],
    paramGroups: [
        { id: "market_general", title: "Общие параметры Маркета", icon: "fa-coins" },
        { id: "steam", title: "Steam / CS2 / Dota", icon: "fa-steam" },
        { id: "telegram", title: "Telegram", icon: "fa-paper-plane" },
        { id: "discord", title: "Discord", icon: "fa-discord" },
        { id: "fortnite", title: "Fortnite", icon: "fa-gamepad" },
        { id: "riot", title: "Valorant / Riot", icon: "fa-crosshairs" },
        { id: "genshin", title: "Genshin Impact", icon: "fa-wand-magic-sparkles" },
        { id: "roblox", title: "Roblox", icon: "fa-cube" },
        { id: "gta5", title: "GTA V", icon: "fa-car" },
        { id: "social", title: "Соцсети (TikTok, Instagram)", icon: "fa-share-nodes" },
        { id: "forum", title: "Форум API", icon: "fa-comments" },
    ],
};
